import { useMemo, useState } from 'react'
import { Button, DatePicker, Form, Input, InputNumber, Modal, Select } from 'antd'
import dayjs from 'dayjs'
import { useNavigate } from 'react-router-dom'
import { toast } from 'react-toastify'
import { apiErrorMessage, useCreatePaymentMutation, useGetDebtorsQuery } from '../../store/baseApi'
import './Debtors.css'

const money = (value) => `${Number(value || 0).toLocaleString('uz-UZ')} so‘m`
const methods = { cash: 'Naqd', online: 'Click', bank: 'Bank', card: 'Karta' }

export function DebtorsPage() {
  const navigate = useNavigate()
  const [paymentForm] = Form.useForm()
  const [period, setPeriod] = useState(dayjs().format('YYYY-MM'))
  const { data, isLoading, error } = useGetDebtorsQuery(period)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [selected, setSelected] = useState(null)
  const [paymentDebtor, setPaymentDebtor] = useState(null)
  const [historyDebtor, setHistoryDebtor] = useState(null)
  const [createPayment, { isLoading: creatingPayment }] = useCreatePaymentMutation()
  const paymentMethod = Form.useWatch('method', paymentForm)
  const selectedInstallmentId = Form.useWatch('installment', paymentForm)
  const selectedPeriod = paymentDebtor?.periods.find((item) => item.id === selectedInstallmentId)
  const debtors = useMemo(() => {
    const needle = query.trim().toLowerCase()
    return (data?.debtors || []).filter((item) => {
      const searchable = `${item.student?.fullName || ''} ${item.student?.phone || ''} ${item.student?.parentPhone || ''} ${item.contracts?.map((contract) => contract.contractNumber).join(' ') || ''} ${item.contracts?.map((contract) => `${contract.room?.block || ''} ${contract.room?.roomNumber || ''}`).join(' ') || ''}`.toLowerCase()
      const statusMatch = status === 'all' || (status === 'overdue' ? item.overdueDebt > 0 : item.debtStatus === status)
      return statusMatch && (!needle || searchable.includes(needle))
    })
  }, [data?.debtors, query, status])
  const summary = data?.summary || {}
  const openPayment = (debtor) => { const first = debtor.periods[0]; setPaymentDebtor(debtor); paymentForm.setFieldsValue({ installment: first?.id, amount: null, method: 'cash', note: '' }) }
  const acceptPayment = async (values) => {
    try {
      const paymentPeriod = paymentDebtor.periods.find((item) => item.id === values.installment)
      await createPayment({ contract: paymentPeriod.contractId, installment: paymentPeriod.id, amount: Number(values.amount), method: values.method, note: values.note || '' }).unwrap()
      toast.success('To‘lov muvaffaqiyatli qabul qilindi'); setPaymentDebtor(null); paymentForm.resetFields()
    } catch (requestError) { toast.error(apiErrorMessage(requestError)) }
  }

  return <div className="debtors-page">
    <section className="debtors-hero"><div><span>TO‘LOV NAZORATI</span><h2>{data?.isFuturePeriod ? 'Kutilayotgan to‘lovlar' : 'Qarzdor talabalar'}</h2><p>Tanlangan oy bo‘yicha to‘lov holatini nazorat qiling.</p></div><DatePicker picker="month" allowClear={false} value={dayjs(period)} format="MMMM YYYY" suffixIcon={<svg className="debtor-calendar-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>} onChange={(date) => setPeriod(date.format('YYYY-MM'))} /></section>
    <section className="debtor-stats"><article className="count"><small>Oy uchun hisoblangan</small><strong>{money(summary.scheduledAmount)}</strong></article><article className="partial"><small>To‘langan summa</small><strong>{money(summary.paidAmount)}</strong></article><article className="total"><small>{data?.isFuturePeriod ? 'Kutilayotgan summa' : 'Qarzdorlik'}</small><strong>{money(data?.isFuturePeriod ? summary.waitingAmount : summary.totalDebt)}</strong></article><article className="overdue"><small>To‘lov qilgan talabalar</small><strong>{summary.paidStudentCount || 0} ta</strong></article><article className="unpaid"><small>{data?.isFuturePeriod ? 'To‘lov kutilmoqda' : 'To‘lov qilmagan'}</small><strong>{summary.noPaymentStudentCount || 0} ta</strong></article></section>
    <section className="debtors-card">
      <div className="debtors-card-head"><div><h3>{data?.isFuturePeriod ? 'To‘lov kutilayotgan talabalar' : 'Qarzdorlar ro‘yxati'}</h3><p>{debtors.length} ta natija · {period}</p></div><div className="debtor-filters"><div className="debtor-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m16.5 16.5 4 4"/></svg><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Talaba, telefon, xona yoki shartnoma" /></div><Select value={status} onChange={setStatus} options={[{ value: 'all', label: 'Barcha talabalar' }, { value: 'overdue', label: 'Muddati o‘tgan' }, { value: 'partial', label: 'Qisman to‘lagan' }, { value: 'unpaid', label: 'Umuman to‘lamagan' }]} /></div></div>
      {error && <div className="form-error">{apiErrorMessage(error)}</div>}
      {isLoading ? <div className="debtor-state">Ma’lumotlar yuklanmoqda…</div> : <div className="debtor-table-wrap"><table className="debtor-table"><thead><tr><th>Talaba</th><th>Universitet</th><th>Xona</th><th>{data?.isFuturePeriod ? 'To‘lov davri' : 'Qarzdor davr'}</th><th>{data?.isFuturePeriod ? 'Kutilayotgan summa' : 'Jami qarz'}</th><th>Muddati o‘tgan</th><th>Oxirgi to‘lov</th><th>Amal</th></tr></thead><tbody>{debtors.map((debtor) => { const room = debtor.contracts?.[0]?.room; return <tr key={debtor.student.id}><td data-label="Talaba"><button className="debtor-student" onClick={() => navigate(`/student/${debtor.student.id}`)}>{debtor.student.photo ? <img src={debtor.student.photo.thumbnailUrl || debtor.student.photo.url} alt="" /> : <span>{debtor.student.fullName?.[0]}</span>}<div><strong>{debtor.student.fullName}</strong><small>{debtor.student.phone}</small></div></button></td><td data-label="Universitet"><strong>{debtor.student.university?.name || '—'}</strong><small>{debtor.student.faculty?.name || ''} · {debtor.student.course}-kurs</small></td><td data-label="Xona">{room ? <><strong>{room.block} · {room.roomNumber}-xona</strong><small>{room.floor}-qavat</small></> : '—'}</td><td data-label="Davrlar"><span className="debt-period-count">{debtor.periodCount} ta davr</span><small>{debtor.periods.map((paymentPeriod) => paymentPeriod.periodKey).join(', ')}</small></td><td data-label="Summa"><b className="debt-money">{money(debtor.totalDebt)}</b></td><td data-label="O‘tgan"><b className={debtor.overdueDebt ? 'overdue-money' : ''}>{money(debtor.overdueDebt)}</b></td><td data-label="Oxirgi to‘lov">{debtor.lastPaymentAt ? <>{dayjs(debtor.lastPaymentAt).format('DD.MM.YYYY')}<small>{money(debtor.lastPaymentAmount)}</small></> : <span className="never-paid">To‘lov qilmagan</span>}</td><td data-label="Amal"><div className="debtor-row-actions"><button className="debtor-pay-btn" onClick={() => openPayment(debtor)}>To‘lov qilish</button><button className="debtor-history-btn" onClick={() => setHistoryDebtor(debtor)} title="To‘lov tarixini ko‘rish"><svg viewBox="0 0 24 24"><path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 4v5h5M12 7v5l3 2"/></svg>Tarix</button><button className="debtor-details-btn" onClick={() => setSelected(debtor)}>Batafsil</button></div></td></tr>})}{!debtors.length && <tr><td colSpan="8" className="debtor-state">Tanlangan oy uchun ma’lumot topilmadi</td></tr>}</tbody></table></div>}
    </section>

    <Modal open={Boolean(selected)} onCancel={() => setSelected(null)} footer={null} width={760} title="Qarzdorlik tafsilotlari" rootClassName="debtor-modal"><>{selected && <div className="debtor-detail"><div className="debtor-detail-person"><div><h3>{selected.student.fullName}</h3><p>{selected.student.university?.name || '—'} · {selected.student.course}-kurs</p></div><div><a href={`tel:${selected.student.phone}`}>{selected.student.phone}</a><a href={`tel:${selected.student.parentPhone}`}>{selected.student.parentPhone || 'Ota-ona telefoni yo‘q'}</a></div></div><div className="debtor-detail-summary"><div><span>Jami qarz</span><strong>{money(selected.totalDebt)}</strong></div><div><span>Muddati o‘tgan</span><strong>{money(selected.overdueDebt)}</strong></div><div><span>Joriy oy</span><strong>{money(selected.currentDebt)}</strong></div></div><h4>Qarzdorlik davrlari</h4><div className="debtor-periods">{selected.periods.map((period) => <article key={period.id}><div><strong>{period.periodKey}</strong><span>{period.contractNumber}</span></div><div><small>Hisoblangan</small><b>{money(period.amount)}</b></div><div><small>To‘langan</small><b className="paid">{money(period.paidAmount)}</b></div><div><small>Qoldiq</small><b className="debt">{money(period.debt)}</b></div><div><small>Muddat</small><b>{dayjs(period.dueDate).format('DD.MM.YYYY')}</b></div></article>)}</div><div className="debtor-detail-actions"><button onClick={() => navigate(`/student/${selected.student.id}`)}>Talaba profilini ochish</button></div></div>}</></Modal>
    <Modal open={Boolean(paymentDebtor)} onCancel={() => setPaymentDebtor(null)} footer={null} width={580} title={paymentDebtor ? `${paymentDebtor.student.fullName} — to‘lov qilish` : 'To‘lov qilish'} rootClassName="debtor-payment-modal" destroyOnHidden><Form form={paymentForm} layout="vertical" requiredMark={false} onFinish={acceptPayment}><Form.Item name="installment" label="Qaysi oy uchun" rules={[{ required: true, message: 'Davrni tanlang' }]}><Select onChange={() => paymentForm.setFieldValue('amount', null)} options={(paymentDebtor?.periods || []).map((paymentPeriod) => ({ value: paymentPeriod.id, label: `${paymentPeriod.periodKey} — ${money(paymentPeriod.debt)} qoldiq` }))} /></Form.Item>{selectedPeriod && <div className="debtor-payment-balance"><span>Tanlangan davr qarzdorligi</span><strong>{money(selectedPeriod.debt)}</strong></div>}<Form.Item name="amount" label="To‘lov summasi" rules={[{ required: true, message: 'Summani kiriting' }]}><InputNumber min={1} max={selectedPeriod?.debt} precision={0} addonAfter="so‘m" formatter={(value) => String(value || '').replace(/\B(?=(\d{3})+(?!\d))/g, ' ')} parser={(value) => String(value || '').replace(/[^\d]/g, '')} /></Form.Item><Form.Item name="method" hidden rules={[{ required: true }]}><Input /></Form.Item><div className="debtor-method-field"><label>To‘lov turi</label><div>{Object.entries(methods).map(([value, label]) => <button type="button" key={value} className={paymentMethod === value ? 'active' : ''} onClick={() => paymentForm.setFieldValue('method', value)}>{label}</button>)}</div></div><Form.Item name="note" label="Izoh"><Input placeholder="Ixtiyoriy" /></Form.Item><div className="debtor-payment-actions"><Button onClick={() => setPaymentDebtor(null)}>Bekor qilish</Button><Button type="primary" htmlType="submit" loading={creatingPayment}>To‘lovni tasdiqlash</Button></div></Form></Modal>
    <Modal open={Boolean(historyDebtor)} onCancel={() => setHistoryDebtor(null)} footer={null} width={760} title={historyDebtor ? `${historyDebtor.student.fullName} — to‘lovlar tarixi` : 'To‘lovlar tarixi'} rootClassName="debtor-history-modal"><div className="debtor-history-wrap"><table className="debtor-history-table"><thead><tr><th>Sana</th><th>Shartnoma</th><th>Qaysi oy uchun</th><th>To‘lov turi</th><th>Summa</th><th>Izoh</th></tr></thead><tbody>{(historyDebtor?.paymentHistory || []).map((payment) => <tr key={payment.id}><td>{dayjs(payment.createdAt).format('DD.MM.YYYY HH:mm')}</td><td>{payment.contract?.contractNumber || '—'}</td><td><span>{payment.allocations?.[0]?.installment?.periodKey || '—'}</span></td><td>{methods[payment.method] || payment.method}</td><td><strong>{money(payment.amount)}</strong></td><td>{payment.note || '—'}</td></tr>)}{!historyDebtor?.paymentHistory?.length && <tr><td colSpan="6" className="debtor-state">To‘lovlar tarixi mavjud emas</td></tr>}</tbody></table></div></Modal>
  </div>
}
